### PR TITLE
Add Old Cart Restore Feature

### PR DESCRIPTION
**Pull request by makwanamahesh-code**
**I added a new feature: Cart Restore After Buy Now Item(s)**

When I placed an order using buy now order was placed successfully but my old cart items were lost. So nowadays many customers do not like this type of process. That’s why I fixed this issue.

**Admin can manage Cart Restore Feature from store configuration.**

screenshot-localhost-2022 06 04-16_02_22

**This new feature works on default Magento single checkout and multi shipping checkout.**

Screenshot

[**Mahesh Makwana**](https://magento.stackexchange.com/users/82670/msquare?tab=profile)

### CODE REVIEW

**Comment by mageprince** [comment]
Hi @maheshmakwana-code Thank you for your contribution. We will verify and merge your changes into the master branch.

**Review by mageprince — CHANGES_REQUESTED** [review]
Hi @maheshmakwana-code, Thank you for your PR.
Can you please update PR with remove overrides core files from `etc/di.xml`? We recommend implementing logic with no core overrides.

**Review by makwanamahesh-code — COMMENTED** [review]
Yes, the same line defines 2 times.

**Comment by maheshmakwana-code** [comment]
@mageprince I have removed the core file override and added new code implementing logic with no core overrides.

**Comment by maheshmakwana-code** [comment]
Hi @mageprince, 

Please verify and merge my changes into the master branch.

Thanks.

**Review by mageprince — CHANGES_REQUESTED** [review]
@maheshmakwana-code Thank you for your PR.

We have tested your changes with fresh Magento installation but products are not able to restore to the cart after placing an order.

Can you please test your changes with fresh Magento installation and feel free to change PR? Thank you for your support.

Magento version: **2.4.4**
Configuration:
image

**Comment by mageprince** [comment]
Hi @maheshmakwana-code We've released the new version 1.4.0 with numerous fixes, improvements, and compatibility testing with Magento and Adobe Commerce 2.4.7. It would be appreciated if you could create a new pull request for the latest release.

**Pull request closed without merging**
